name: YYF
# config flie for sae rewrite
handle:
- rewrite: if(path == "/robots.txt") goto "/public/robots.txt"
- rewrite: if(path == "/favicon.ico") goto "/public/favicon.ico"
- rewrite: if(path~"^(.*)$") goto "/public/index.php/$1"

- hostaccess: if (%{REQUEST_URI} ~*"/conf/") allow "0.0"
- hostaccess: if (%{REQUEST_URI} ~*"/app/")  allow "0.0"
- hostaccess: if (path ~*".htacesss")  allow "0.0"